name: ScoreboardAPI
main: jasonwynn10\ScoreboardAPI\ScoreboardAPI
version: 1.0.3
api: 3.3.0
author: "jasonwynn10"
description: "A simple API for creating scoreboards on PocketMine-MP servers"
load: STARTUP
mcpe-protocols:
  - 419